### ISSUE TITLE
Change zokrates-js to point to master

### ISSUE THREAD

**Issue by Schaeff** [Zokrates/zokrates-js#4]
Right now zokrates-js points to the `wasm-friendly` branch as master is not wasm friendly. This is fine for now but zokrates-js should be moved to point to master once `wasm-friendly` is merged.

Deployment to npm should be automated in the main zokrates repo when releasing.

Blocking this: https://github.com/Zokrates/ZoKrates/issues/497

**Comment by edisinovcic** [comment]
Update https://github.com/Zokrates/ZoKrates/blob/master/scripts/release.sh to have publish zokrate-js to npm
