### ISSUE TITLE
recursive imports not supported

### ISSUE THREAD

**Issue by alv-around** [Zokrates/zokrates-js#7]
I am trying to compile a zok file which imports "ecc/proofOfOwnership" and get the following error:

`Unable to resolve ecc/edwardsAdd` 

I import in previous lines other functions (ex: `ecc/babyjubjubParams`). So I copied the code of proofOfOwnership in my file and I get the following:

`ecc/edwardsAdd:1:1
        Unable to resolve ecc/babyjubjubParams`

I think recursive imports (importing from imported files) is not supported. The only workaround I can think sofar is flattening all imported files which also import something else

**Comment by dark64** [comment]
Hey @alvaro-alonso, this repository is outdated. This issue has been fixed with latest release of zokrates-js `^1.0.19`. As for the remix plugin, we will release a new version soon.
